In [11]:
import pandas as pd
from tqdm.auto import tqdm

In [4]:
ecfp0 = list()
ecfp1 = list()
ecfp2 = list()

In [5]:
# read from files
for i in tqdm(range(20)):
    data_chunk = pd.read_hdf(f'data_10M/data_mol/data{i}.h5')
    for efcp in tqdm(data_chunk['ECFP']):
        ecfp0.append(efcp[0])
        ecfp1.append(efcp[1])
        ecfp2.append(efcp[2])

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

  0%|          | 0/500000 [00:00<?, ?it/s]

In [8]:
def write_to_file(name: str, efcp_dataset):
    with open(f'efcps_full/{name}.txt', 'w+') as f:
        for ecpf in efcp_dataset:
            for number in ecpf:
                f.write(number)
                f.write(' ')
            f.write('\n')

In [9]:
write_to_file('ecfp0', ecfp0)
write_to_file('ecfp1', ecfp1)
write_to_file('ecfp2', ecfp2)

In [12]:
data_chunk = pd.read_hdf(f'data_10M/data_mol/data0.h5')

In [15]:
# example
data_chunk['ECFP'][0]

[['2246728737',
  '848128881',
  '3217380708',
  '3218693969',
  '3218693969',
  '3218693969',
  '3218693969',
  '3218693969',
  '3217380708',
  '3218693969',
  '3218693969',
  '3218693969',
  '3218693969',
  '3217380708',
  '2246699815',
  '864942730',
  '847961216',
  '2245384272',
  '2976816164',
  '864662311',
  '2968968094',
  '2968968094',
  '3189457552',
  '2968968094',
  '2968968094'],
 ['3818546315',
  '1898153655',
  '1449131080',
  '951226070',
  '98513984',
  '98513984',
  '98513984',
  '951226070',
  '1534595042',
  '951226070',
  '98513984',
  '98513984',
  '951226070',
  '2309124039',
  '1054767590',
  '1510328189',
  '717512901',
  '4203187903',
  '2026801565',
  '265892994',
  '2119439498',
  '1257718710',
  '3203709451',
  '1257718710',
  '2119439498'],
 ['1151493923',
  '2434874479',
  '2739425568',
  '3999906991',
  '2763854213',
  '3999906991',
  '2739425568',
  '3776989082',
  '2688578898',
  '3999906991',
  '3999906991',
  '2987120039',
  '2054202824',
  '2843970

In [2]:
from dgl.data import QM9

In [3]:
dataset = QM9(label_keys=["mu"])

/home/alexeyorlov53/.dgl/qm9_eV.npz:   0%|          | 0.00/83.8M [00:00<?, ?B/s]

In [4]:
dataset

Dataset("qm9", num_graphs=130831, save_path=/home/alexeyorlov53/.dgl/qm9_05cd79f0)

In [5]:
print(dataset)

Dataset("qm9", num_graphs=130831, save_path=/home/alexeyorlov53/.dgl/qm9_05cd79f0)


In [7]:
for g, label in dataset:
    print(g)
    print(label)
    print(g.ndata['R'])
    print(g.ndata['Z'])
    break

Graph(num_nodes=5, num_edges=20,
      ndata_schemes={'R': Scheme(shape=(3,), dtype=torch.float32), 'Z': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={})
tensor([0.])
tensor([[-1.2698e-02,  1.0858e+00,  8.0010e-03],
        [ 2.1504e-03, -6.0313e-03,  1.9761e-03],
        [ 1.0117e+00,  1.4638e+00,  2.7657e-04],
        [-5.4082e-01,  1.4475e+00, -8.7664e-01],
        [-5.2381e-01,  1.4379e+00,  9.0640e-01]])
tensor([6, 1, 1, 1, 1])
